name: mcbans
main: com.mcbans.firestar.mcbans.bukkitInterface
version: 3.0p
author: Firestar
commands:
  kick:
    description: kicks a user
    usage: /<command> <playername> [reason]
  ban:
    description: ban a user
    usage: /<command> <playername> [g/reason] [reason]
  unban:
    description: unban a user
    usage: /<command> <playername>
  tempban:
    description: temporary ban user
    usage: /<command> <playername> <duration> <m(minutes) or h(hours) or d(days)> [reason]
  lookup:
    description: lookup a player
    usage: /<command> <playername>
  lup:
    description: alias of lookup
    usage: /<command> <playername>
  mcbans:
    description: player set
    usage: /<command> <playername>
  inbox:
    description: player set
    usage: /<command> <playername>
  read:
    description: player set
    usage: /<command> <playername>
  send:
    description: player set
    usage: /<command> <playername>
  block:
    description: player set
    usage: /<command> <playername>
  unblock:
    description: player set
    usage: /<command> <playername>
  binbox:
    description: player set
    usage: /<command> <playername>
  bread:
    description: player set
    usage: /<command> <playername>
  bsend:
    description: player set
    usage: /<command> <playername>
  bblock:
    description: player set
    usage: /<command> <playername>
  bunblock:
    description: player set
    usage: /<command> <playername>