name: mcbans
main: com.mcbans.firestar.mcbans.BukkitInterface
version: 3.9
description: A global banning solution (http://mcbans.com)
softdepend: [LogBlock, HawkEye, CoreProtect]
author: Firestar, Syamn
commands:
  kick:
    description: kicks a user
    usage: /<command> <playername> [reason]
  ban:
    description: ban a user
    usage: /<command> <playername> [g/t/reason] [reason]
  gban:
    description: global bans a user
    usage: /<command> <playername> [reason]
  rban:
    description: roll back bans
    usage: /<command> <playername> [g/t/reason] [reason]
  unban:
    description: unban a user
    usage: /<command> <playername>
  tempban:
    description: temporary ban user
    aliases: [tban]
    usage: /<command> <playername> <duration> <m(minutes) or h(hours) or d(days)> [reason]
  lookup:
    description: lookup a player
    aliases: [lup]
    usage: /<command> <playername>
  mcbans:
    description: mcbans functions
    usage: /<command> <function>
permissions:
  mcbans.admin:
    description: Admin priveleges to mcbans, onconnect globals visible
    default: op
  mcbans.kick.view:
    description: Display kick message to anyone with this permission
    default: op
  mcbans.join.view:
    description: Join messages
    default: op
  mcbans.alts.hide:
    description: Hide notification of alts on connect
    default: op
  mcbans.alts.view:
    description: show notification of a players alts on connect
    default: op
  mcbans.ban.view:
    description: View ban information on user joining
    default: op
  mcbans.ban.global:
    description: Give global bans
    default: op
  mcbans.ban.local:
    description: Give local bans
    default: op
  mcbans.ban.rollback:
    description: Gives rban commands
    default: op
  mcbans.ban.temp:
    description: Give temp bans
    default: op
  mcbans.unban:
    description: Unban users
    default: op
  mcbans.lookup:
    description: Lookup ban history on command
    default: op
  mcbans.kick:
    description: Kick users
    default: op
  mcbans.mode:
    description: Change between online and offline modes
    default: op
  mcbans.all:
    description: All permissions
    children:
      mcbans.ban.view: true
      mcbans.alts.hide: true
      mcbans.alts.view: true
      mcbans.join.view: true
      mcbans.ban.global: true
      mcbans.ban.local: true
      mcbans.ban.temp: true
      mcbans.unban: true
      mcbans.lookup: true
      mcbans.admin: true
      mcbans.kick: true
      mcbans.kick.view: true
      mcbans.mode: true
